[workspace]
members = [
    "hermit-abi",
    "hermit-sys",
    "benches/netbench",
    "benches/micro",
    "examples/hello_world",
    "examples/httpd",
    "examples/demo",
]
exclude = ["target", "libhermit-rs"]

[patch.crates-io]
os_str_bytes = { git = 'https://github.com/hermitcore/os_str_bytes.git', branch = 'hermit' }
