[workspace]
members = [
    "hermit-abi",
    "hermit-sys",
    "benches/netbench",
    "benches/micro",
    "examples/hello_world",
    "examples/httpd",
    "examples/demo",
]
exclude = ["target", "loader", "libhermit-rs"]

[profile.release]
opt-level = 2

[profile.dev]
opt-level = 1
