[workspace]
resolver = "2"
members = [
    "benches/alloc",
    "benches/micro",
    "benches/netbench",
    "examples/demo",
    "examples/fuse_test",
    "examples/hello_world",
    "examples/httpd",
    "examples/testtcp",
    "examples/testudp",
    "examples/polling",
    "examples/miotcp",
    "examples/mioudp",
    "examples/tokio",
    "examples/webserver",
    "examples/tls",
    "hermit",
    "hermit-abi",
]

[patch.crates-io]
socket2 = { git = "https://github.com/hermit-os/socket2.git", branch = "hermit" }
tokio = { git = "https://github.com/hermit-os/tokio.git", branch = "hermit" }
hyper-util = { git = "https://github.com/hermit-os/hyper-util.git", branch = "hermit" }
mio = { git = "https://github.com/hermit-os/mio.git", branch = "v0.8.x" }
tokio-rustls = { git = "https://github.com/hermit-os/tokio-rustls.git", branch = "hermit" }
