[package]
name = "httpd"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ascii = "1.0"
tiny_http = { git = "https://github.com/hermitcore/tiny-http.git" }

[target.'cfg(all(any(target_arch = "x86_64", target_arch = "aarch64"), target_os = "hermit"))'.dependencies.hermit-sys]
path = "../../hermit-sys"
default-features = false
features = ["with_submodule"]

[features]
default = ["pci", "acpi", "smoltcp"]
vga = ["hermit-sys/vga"]
dhcpv4 = ["hermit-sys/dhcpv4"]
pci = ["hermit-sys/pci"]
acpi = ["hermit-sys/acpi"]
fsgsbase = ["hermit-sys/fsgsbase"]
smp = ["hermit-sys/smp"]
smoltcp = ["hermit-sys/smoltcp"]
instrument = ["hermit-sys/instrument"]
