[package]
name = "httpd"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ascii = "1.0"
tiny_http = { git = "https://github.com/hermitcore/tiny-http.git" }

[target.'cfg(target_os = "hermit")'.dependencies.hermit-sys]
path = "../../hermit-sys"
default-features = false
features = ["acpi", "pci", "tcp", "with_submodule"]
