[package]
name = "httpd"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ascii = "1.0"
tiny_http = { git = "https://github.com/hermitcore/tiny-http.git" }

[target.'cfg(target_os = "hermit")'.dependencies.hermit-sys]
path = "../../hermit-sys"
default-features = false

[features]
default = ["pci", "acpi", "tcp"]
vga = ["hermit-sys/vga"]
dhcpv4 = ["hermit-sys/dhcpv4"]
pci = ["hermit-sys/pci"]
acpi = ["hermit-sys/acpi"]
fsgsbase = ["hermit-sys/fsgsbase"]
smp = ["hermit-sys/smp"]
tcp = ["hermit-sys/tcp"]
instrument = ["hermit-sys/instrument"]
